"""PDF 책 구조화 패키지의 공개 API다."""

from pdfbooktree.artifacts import write_inference_artifacts
from pdfbooktree.batch import BatchProcessor
from pdfbooktree.batch_run import (
    BATCH_RUN_MANIFEST_SCHEMA_VERSION,
    BatchItemRunReference,
    BatchRunContext,
    BatchRunError,
    BatchRunManifest,
    BatchRunSummary,
    create_batch_run_context,
)
from pdfbooktree.config import (
    ConfigError,
    MarkdownSplitConfig,
    OutlineQualityConfig,
    ProcessingConfig,
    TypographyConfig,
)
from pdfbooktree.cli_contract import (
    CLI_RESULT_SCHEMA_VERSION,
    CommandError,
    CommandErrorEnvelope,
    CommandResultEnvelope,
    ProcessingFailedError,
)
from pdfbooktree.config_io import ResolvedConfig, resolve_processing_config
from pdfbooktree.evaluation import (
    DEFAULT_COMPARE_PAGE_TOLERANCE,
    DEFAULT_PAGE_TOLERANCE,
    DEFAULT_TITLE_SIMILARITY_THRESHOLD,
    MatchedPair,
    MatchMetrics,
    PlanDiffEntry,
    PlanDiffResult,
    compare_bookmark_plans,
    match_bookmark_plans,
    PlanMatchResult,
)
from pdfbooktree.inspection import (
    inspect_bookmarks,
    inspect_compare_plans,
    inspect_ocr_artifact,
    inspect_page_count,
    inspect_plan_artifact,
    inspect_text,
)
from pdfbooktree.models import (
    ApplyResult,
    BatchItemResult,
    BatchResult,
    BookmarkInferenceResult,
    BookmarkPlanItem,
    BookmarkPlanValidation,
    BookmarkTreeNode,
    ConfidenceSummary,
    ExistingOutlineItem,
    HeadingCandidate,
    MarkdownExportResult,
    MarkdownFileStat,
    OutlineQualityAssessment,
    PdfAnalysis,
    ProcessingResult,
    Tier,
    TierSet,
    TypographyLine,
)
from pdfbooktree.outline.plan_io import PlanError, load_bookmark_plan_json
from pdfbooktree.pdf.outline_quality import assess_outline_quality
from pdfbooktree.pipeline import (
    analyze_pdf,
    apply_plan,
    confidence_summary_for_inference,
    infer_bookmarks,
    resolve_existing_outline_action,
)
from pdfbooktree.processor import Processor
from pdfbooktree.project_skill import (
    PROJECT_SKILL_NAME,
    PROJECT_SKILL_RELATIVE_PATH,
    SkillInstallError,
    SkillInstallResult,
    install_project_skill,
)
from pdfbooktree.run import (
    InputIdentity,
    RunContext,
    RunError,
    RunManifest,
    ToolIdentity,
    create_run_context,
)

__all__ = [
    "analyze_pdf",
    "apply_plan",
    "ApplyResult",
    "CLI_RESULT_SCHEMA_VERSION",
    "assess_outline_quality",
    "BATCH_RUN_MANIFEST_SCHEMA_VERSION",
    "BatchItemRunReference",
    "BatchProcessor",
    "BatchItemResult",
    "BatchResult",
    "BatchRunContext",
    "BatchRunError",
    "BatchRunManifest",
    "BatchRunSummary",
    "BookmarkInferenceResult",
    "BookmarkPlanItem",
    "BookmarkPlanValidation",
    "BookmarkTreeNode",
    "ConfidenceSummary",
    "CommandError",
    "CommandErrorEnvelope",
    "CommandResultEnvelope",
    "ProcessingFailedError",
    "confidence_summary_for_inference",
    "ConfigError",
    "compare_bookmark_plans",
    "DEFAULT_COMPARE_PAGE_TOLERANCE",
    "DEFAULT_PAGE_TOLERANCE",
    "DEFAULT_TITLE_SIMILARITY_THRESHOLD",
    "ExistingOutlineItem",
    "HeadingCandidate",
    "infer_bookmarks",
    "install_project_skill",
    "match_bookmark_plans",
    "MatchedPair",
    "MatchMetrics",
    "inspect_bookmarks",
    "inspect_compare_plans",
    "inspect_ocr_artifact",
    "inspect_page_count",
    "inspect_plan_artifact",
    "inspect_text",
    "load_bookmark_plan_json",
    "MarkdownExportResult",
    "MarkdownFileStat",
    "MarkdownSplitConfig",
    "OutlineQualityAssessment",
    "OutlineQualityConfig",
    "PdfAnalysis",
    "PlanDiffEntry",
    "PlanDiffResult",
    "PlanError",
    "PlanMatchResult",
    "ProcessingConfig",
    "ProcessingResult",
    "Processor",
    "PROJECT_SKILL_NAME",
    "PROJECT_SKILL_RELATIVE_PATH",
    "resolve_existing_outline_action",
    "ResolvedConfig",
    "resolve_processing_config",
    "RunContext",
    "RunError",
    "RunManifest",
    "SkillInstallError",
    "SkillInstallResult",
    "InputIdentity",
    "ToolIdentity",
    "create_run_context",
    "create_batch_run_context",
    "Tier",
    "TierSet",
    "TypographyConfig",
    "TypographyLine",
    "write_inference_artifacts",
]
